trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:

# ---------------- CI ----------------
- stage: Build
  jobs:
  - job: BuildJob
    steps:

    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: '8.x'

    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: drop


# ---------------- DEV ----------------
- stage: Dev
  dependsOn: Build
  jobs:
  - deployment: DeployDev
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Azure-Service-Connection'
              appName: 'dotnetwebapp-sushr'
              package: '$(Pipeline.Workspace)/drop/**/*.zip'


# ---------------- STAGING ----------------
- stage: Staging
  dependsOn: Dev
  jobs:
  - deployment: DeployStaging
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Azure-Service-Connection'
              appName: 'dotnetwebapp-staging'
              package: '$(Pipeline.Workspace)/drop/**/*.zip'


# ---------------- PRODUCTION ----------------
- stage: Production
  dependsOn: Staging
  jobs:
  - deployment: DeployProd
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Azure-Service-Connection'
              appName: 'dotnetwebapp-prod'
              package: '$(Pipeline.Workspace)/drop/**/*.zip'